AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "spec/support/fixtures/**/*"
    - "vendor/**/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "evilution.gemspec"

# target 150
Metrics/ClassLength:
  Max: 150
  Exclude:
    - "lib/evilution/runner/mutation_executor.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/evilution/reporter/suggestion/templates/rspec.rb"
    - "lib/evilution/reporter/suggestion/templates/minitest.rb"

# target 20
Metrics/MethodLength:
  Max: 30
  CountAsOne:
    - array
    - hash
    - heredoc

# target 17
Metrics/AbcSize:
  Max: 30

# target 7
Metrics/CyclomaticComplexity:
  Max: 12

# target 8
Metrics/PerceivedComplexity:
  Max: 8

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - "lib/evilution/integration/rspec.rb"

Layout/LineLength:
  Max: 140

Naming/MethodParameterName:
  MinNameLength: 1

Lint/MissingSuper:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/FloatComparison:
  Exclude:
    - "lib/evilution/mutator/operator/float_literal.rb"

Lint/DuplicateBranch:
  Exclude:
    - "lib/evilution/mutator/operator/float_literal.rb"

Lint/UselessMethodDefinition:
  Exclude:
    - "spec/fixtures/**/*"

Naming/PredicateMethod:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
