# frozen_string_literal: true

require_relative "evilution/version"
require_relative "evilution/memory"
require_relative "evilution/config"
require_relative "evilution/subject"
require_relative "evilution/result"
require_relative "evilution/mutation"
require_relative "evilution/ast"
require_relative "evilution/parallel"
require_relative "evilution/ast/source_surgeon"
require_relative "evilution/ast/parser"
require_relative "evilution/ast/inheritance_scanner"
require_relative "evilution/hooks"
require_relative "evilution/mutator"
require_relative "evilution/mutator/base"
require_relative "evilution/mutator/operator"
require_relative "evilution/mutator/operator/comparison_replacement"
require_relative "evilution/mutator/operator/boolean_literal_replacement"
require_relative "evilution/mutator/operator/integer_literal"
require_relative "evilution/mutator/operator/float_literal"
require_relative "evilution/mutator/operator/nil_replacement"
require_relative "evilution/mutator/operator/boolean_operator_replacement"
require_relative "evilution/mutator/operator/arithmetic_replacement"
require_relative "evilution/mutator/operator/string_literal"
require_relative "evilution/mutator/operator/array_literal"
require_relative "evilution/mutator/operator/hash_literal"
require_relative "evilution/mutator/operator/conditional_branch"
require_relative "evilution/mutator/operator/symbol_literal"
require_relative "evilution/mutator/operator/conditional_negation"
require_relative "evilution/mutator/operator/negation_insertion"
require_relative "evilution/mutator/operator/statement_deletion"
require_relative "evilution/mutator/operator/method_body_replacement"
require_relative "evilution/mutator/operator/return_value_removal"
require_relative "evilution/mutator/operator/collection_replacement"
require_relative "evilution/mutator/operator/method_call_removal"
require_relative "evilution/mutator/operator/argument_removal"
require_relative "evilution/mutator/operator/block_removal"
require_relative "evilution/mutator/operator/conditional_flip"
require_relative "evilution/mutator/operator/range_replacement"
require_relative "evilution/mutator/operator/regexp_mutation"
require_relative "evilution/mutator/operator/receiver_replacement"
require_relative "evilution/mutator/operator/send_mutation"
require_relative "evilution/mutator/operator/argument_nil_substitution"
require_relative "evilution/mutator/operator/compound_assignment"
require_relative "evilution/mutator/operator/mixin_removal"
require_relative "evilution/mutator/operator/superclass_removal"
require_relative "evilution/mutator/operator/local_variable_assignment"
require_relative "evilution/mutator/operator/instance_variable_write"
require_relative "evilution/mutator/operator/class_variable_write"
require_relative "evilution/mutator/operator/global_variable_write"
require_relative "evilution/mutator/operator/rescue_removal"
require_relative "evilution/mutator/operator/rescue_body_replacement"
require_relative "evilution/mutator/operator/inline_rescue"
require_relative "evilution/mutator/operator/ensure_removal"
require_relative "evilution/mutator/operator/break_statement"
require_relative "evilution/mutator/operator/next_statement"
require_relative "evilution/mutator/operator/redo_statement"
require_relative "evilution/mutator/operator/bang_method"
require_relative "evilution/mutator/operator/bitwise_replacement"
require_relative "evilution/mutator/operator/bitwise_complement"
require_relative "evilution/mutator/operator/zsuper_removal"
require_relative "evilution/mutator/operator/explicit_super_mutation"
require_relative "evilution/mutator/operator/index_to_fetch"
require_relative "evilution/mutator/operator/index_to_dig"
require_relative "evilution/mutator/operator/index_assignment_removal"
require_relative "evilution/mutator/registry"
require_relative "evilution/equivalent"
require_relative "evilution/equivalent/heuristic"
require_relative "evilution/equivalent/detector"
require_relative "evilution/isolation"
require_relative "evilution/isolation/fork"
require_relative "evilution/isolation/in_process"
require_relative "evilution/parallel/pool"
require_relative "evilution/session"
require_relative "evilution/session/store"
require_relative "evilution/git"
require_relative "evilution/git/changed_files"
require_relative "evilution/integration"
require_relative "evilution/integration/base"
require_relative "evilution/integration/rspec"
require_relative "evilution/result/mutation_result"
require_relative "evilution/result/summary"
require_relative "evilution/reporter"
require_relative "evilution/reporter/json"
require_relative "evilution/reporter/cli"
require_relative "evilution/reporter/html"
require_relative "evilution/reporter/suggestion"
require_relative "evilution/reporter/progress_bar"
require_relative "evilution/spec_resolver"
require_relative "evilution/baseline"
require_relative "evilution/cache"
require_relative "evilution/cli"
require_relative "evilution/runner"

module Evilution
  class Error < StandardError
    attr_reader :file

    def initialize(message = nil, file: nil)
      super(message)
      @file = file
    end
  end

  class ConfigError < Error; end
  class ParseError < Error; end
  class IsolationError < Error; end
end
