name: Bundle Audit

on:
  push: {}

jobs:
  bundle-audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '3.4.9'
          - '4.0.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Perform bundle audit
        run: bundle exec bundle-audit check
