name: Bundle Audit

on:
  push: {}

jobs:
  bundle-audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '3.4.9'
          - '4.0.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # v1.301.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Perform bundle audit
        run: bundle exec bundle-audit check
