name: Ruby

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.10'
          - '3.4.8'
          - '4.0.1'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop

      - name: Run tests
        run: |
          if [ "${{ env.SKIP_PARALLEL_POOL_SPEC }}" = "1" ]; then
            bundle exec rspec --exclude-pattern "spec/evilution/parallel/pool_spec.rb"
          else
            bundle exec rspec spec
          fi
        timeout-minutes: 5
