name: Lint and Test

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.10'
          - '3.4.8'
          - '4.0.1'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@9d13dd6ce2979b207024f719160a99112fb38eea # v1.291.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec spec
        timeout-minutes: 5
